version: '3.7'

services:

  nginx:
    build:
      context: ./docker/development/nginx
      dockerfile: Dockerfile
    volumes:
      - ./:/app
    restart: always
    depends_on:
      - php-fpm
    ports:
      - ${NGINX_EXTERNAL_PORT}:80

  php-fpm:
    build:
      context: docker/development/php-fpm
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?serverVersion=13&charset=utf8
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: pgsql://${DB_ROOT_PASSWORD}:${DB_ROOT_PASSWORD}@${DB_HOST}:5432/${DB_TEST_NAME}?serverVersion=13&charset=utf8
      APP_ENV: dev
    restart: always
    depends_on:
      - db
    volumes:
      - ./:/app

  php-cli:
    build:
      context: docker/development/php-cli
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: pgsql://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:5432/${DB_NAME}?serverVersion=13&charset=utf8
      APP_SECRET: 8d6efe5f71a7c9a3c6c2854d44fed71d
      TEST_DATABASE_URL: pgsql://${DB_ROOT_PASSWORD}:${DB_ROOT_PASSWORD}@${DB_HOST}:5432/${DB_TEST_NAME}?serverVersion=13&charset=utf8
      APP_ENV: dev
    depends_on:
      - db
    volumes:
    - ./:/app

  db:
    image: postgres:13.3-alpine
    volumes:
      - db:/var/lib/postgresql/data
    restart: always
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - ${DB_PORT_EXTERNAL}:5432

volumes:
  db:
